const fs = require('fs');
const path = require('path');

async function generateReport() {
  console.log('📊 Generating test report...');
  
  // Chạy attack tests
  const { runAllAttacks } = require('../backend/attack-scripts/attack-runner');
  const results = await runAllAttacks();
  
  // Tạo report
  const timestamp = new Date().toISOString();
  const total = results.length;
  const passed = results.filter(r => r.passed).length;
  const failed = total - passed;
  const passRate = total > 0 ? Math.round((passed / total) * 100) : 0;
  
  let report = `# 📊 Capyvocab Security Test Report\n\n`;
  report += `**Generated:** ${timestamp}\n\n`;
  report += `## 📈 Summary\n\n`;
  report += `| Metric | Value |\n`;
  report += `|--------|-------|\n`;
  report += `| Total Tests | ${total} |\n`;
  report += `| Passed | ${passed} |\n`;
  report += `| Failed | ${failed} |\n`;
  report += `| Pass Rate | ${passRate}% |\n\n`;
  
  report += `## 📋 Detailed Results\n\n`;
  report += `| # | Test | Result | Details |\n`;
  report += `|---|------|--------|---------|\n`;
  
  results.forEach((r, i) => {
    const status = r.passed ? '✅ PASS' : '❌ FAIL';
    const details = r.message || r.details ? JSON.stringify(r.details).substring(0, 50) : '-';
    report += `| ${i + 1} | ${r.name || 'Unknown'} | ${status} | ${details} |\n`;
  });
  
  report += `\n---\n`;
  report += `*Generated by Capyvocab Security System*\n`;
  
  // Lưu report
  const reportPath = path.join(__dirname, '../docs/test-results.md');
  fs.writeFileSync(reportPath, report);
  
  console.log(`✅ Report saved to: ${reportPath}`);
  console.log(`📊 ${passed}/${total} tests passed (${passRate}%)`);
}

generateReport().catch(console.error);